title: NBS
description: National Electronic Disease Surveillance System Base System (NBS)
theme: just-the-docs
url: https://njaved.github.io/just-the-doc
aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://njaved.github.io/just-the-doc
color_scheme: custome_scheme
