title: NBS 7.9 System Administrator Guide
description: National Electronic Disease Surveillance System Base System (NBS)
theme: just-the-docs
url: https://njaved.github.io/just-the-doc

# Enable the custom stylesheet
just_the_docs:
  palette:
    primary:
      color: "#000000"
      text-color: "#ffffff"
  custom_css:
    - assets/css/custom.css
