title: NBS 7.9 System Administrator Guide
description: National Electronic Disease Surveillance System Base System (NBS) System Administrator Guide
theme: just-the-docs
url: https://njaved.github.io/just-the-doc
aux_links: # remove if you don't want this link to appear on your pages
  GitHub Repository: https://njaved.github.io/just-the-doc
color_scheme: colors
#logo: "/assets/images/just-the-docs.png"