title: National Electronic Disease Surveillance System Base System (NBS)
description: National Electronic Disease Surveillance System Base System (NBS)
theme: just-the-docs

url: https://njaved.github.io/just-the-doc

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/njaved/just-the-doc
